# Generated by Django 5.1.2 on 2024-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaVerde', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
