# Generated by Django 5.1.2 on 2024-10-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaVerde', '0003_pedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
